Repository svelte-on-solana/wallet-adapter, pull requests merged in 2022-05, with the labels that each got.

#27 Allow the number of wallets shown in the modal to be configured when …
  packages/ui/README.md
  packages/ui/src/lib/WalletModal.svelte
  packages/ui/src/lib/WalletMultiButton.svelte
Labels: enhancement

#29 enhancement:walletstore-type-exportable
  packages/core/src/walletStore.ts
Labels: enhancement

#30 feature:update-packages
  packages/anchor/package.json
  packages/core/package.json
Labels: feature

#32 bug:anchor-provider-not-a-constructor
  packages/anchor/README.md
  packages/anchor/src/lib/AnchorConnectionProvider.svelte
  packages/anchor/svelte.config.js
Labels: bug

#33 enhancement:new-UI-style
  packages/core/src/walletStore.ts
  packages/ui/src/lib/WalletButton.svelte
  packages/ui/src/lib/WalletModal.svelte
  packages/ui/src/lib/WalletMultiButton.svelte
  packages/ui/src/lib/styles.css
Labels: enhancement

#34 bug:import-style-ui
  packages/ui/src/lib/WalletMultiButton.svelte
Labels: bug

#36 bug/dropdown-not-sync-correctly
  packages/ui/src/lib/WalletMultiButton.svelte
Labels: bug
